import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np
import re
import inspect
import plotly.io as pio
import io
from PyPDF2 import PdfMerger

def execute_visualization_code(code, df):
    """
    Execute the visualization code generated by the AI.
    
    Args:
        code: String containing Python code with visualization functions
        df: Pandas DataFrame containing the data
    """
    try:
        # Create a namespace to execute the code
        namespace = {
            'df': df,
            'px': px,
            'go': go,
            'make_subplots': make_subplots,
            'np': np
        }
        
        # Execute the code
        exec(code, namespace)
        
        # Find visualization functions
        viz_funcs = sorted([f for f in namespace if f.startswith('viz_') and callable(namespace[f])])
        
        if not viz_funcs:
            print("No visualization functions found in the generated code.")
            # st.warning("No visualization functions found in the generated code.")
        else:
            # Create a container for visualizations
            st.markdown("### Generated Data Visualizations")
            
            figs = []  # Collect figures here

            # Display each visualization with its corresponding question
            for viz_func_name in viz_funcs:
                viz_func = namespace[viz_func_name]
                try:
                    # Create a container for this visualization
                    viz_container = st.container()
                    with viz_container:
                        # st.markdown(f"#### Visualization {viz_func_name.split('_')[1]}")
                        
                        # Check if the function accepts a 'df' parameter
                        sig = inspect.signature(viz_func)
                        if 'df' in sig.parameters:
                            fig = viz_func(df)  # Pass the dataframe to the function
                        else:
                            fig = viz_func()  # Call without parameters
                        
                        figs.append(fig)  # Collect the figure
                        st.session_state.figs.append(fig)  # Store the figure in session state
                        # Display the figure
                        st.plotly_chart(fig, use_container_width=True)
                        
                except Exception as e:
                    print(f"Error in visualization {viz_func_name}: {str(e)}")
                    # st.error(f"Error in visualization {viz_func_name}: {str(e)}")
                    
            # --- Download buttons ---
            # if figs:
            #     # HTML download
            #     custom_colors = ['#636EFA', '#EF553B', '#00CC96', '#AB63FA', '#FFA07A', '#FF7F0E', '#7F7F7F']
            #     html_buf = io.StringIO()
            #     for fig in figs:
            #         html_buf.write(pio.to_html(fig, full_html=False, include_plotlyjs='cdn'))
            #         fig.update_layout(colorway=custom_colors)
            #     # html_content = f"<html><head></head><body>{html_buf.getvalue()}</body></html>"
            #     html_content = f"""
            #                     <html>
            #                     <head>
            #                         <meta charset="utf-8">
            #                         <title>Visualizations</title>
            #                     </head>
            #                     <body>
            #                         {html_buf.getvalue()}
            #                     </body>
            #                     </html>
            #                     """
            #     st.download_button(
            #         label="⬇️ Download All Visualizations (HTML)",
            #         data=html_content,
            #         file_name="visualizations.html",
            #         mime="text/html"
            #     )

            #     # PDF download (static images)
            #     pdf_merger = PdfMerger()
            #     pdf_buffers = []
            #     for i, fig in enumerate(figs):
            #         pdf_bytes = fig.to_image(format="pdf")
            #         pdf_buf = io.BytesIO(pdf_bytes)
            #         pdf_buffers.append(pdf_buf)
            #         pdf_merger.append(pdf_buf)
            #     if pdf_buffers:
            #         merged_pdf = io.BytesIO()
            #         pdf_merger.write(merged_pdf)
            #         pdf_merger.close()
            #         merged_pdf.seek(0)
            #         print("PDF generated successfully.")
            #         st.download_button(
            #             label="⬇️ Download All Visualizations (PDF)",
            #             data=merged_pdf,
            #             file_name="visualizations.pdf",
            #             mime="application/pdf"
                    # )
    except Exception as e:
        print(f"Error executing visualization code: {str(e)}")
        # st.error(f"Error executing visualization code: {str(e)}")